### ISSUE TITLE
Function app deployment does not work when using managed identity to connect to storage

### ISSUE THREAD

**Issue by krisnyl** [Azure/ResourceModules#1195]
## Description

When using managed identity to connect to storage in Function apps, the AzureWebJobsStorage app setting must not be present. The template currently adds the setting with an empty value instead of not adding it at all when not specifying a storage account.

**Comment by lsnoddy** [comment]
@krisnyl, can you provide steps to re-produce? Does the deployment actually fail?

**Comment by krisnyl** [comment]
The deployment does not fail, but the function will not start if the "AzureWebJobsStorage" app setting is present and empty.

**Comment by lsnoddy** [comment]
There are two pull requests (https://github.com/Azure/ResourceModules/pull/1258) and (draft - https://github.com/Azure/ResourceModules/pull/1239) that change how "AzureWebJobsStorage" is added to app settings. Essentially, this setting is required by azure functions for normal operation and should only be added with a storage account connection string. I don't think this is directly related to using managed identity as they should be able to co-exist. Once the pull requests have been merged, I will test to make sure this functions properly.

There is also a preview feature (described here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#use-managed-identity-for-azurewebjobsstorage-preview and https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#connecting-to-host-storage-with-an-identity-preview) for using managed identity with "AzureWebJobsStorage" that will need to be evaluated as it requires changes to the setting:
AzureWebJobsStorage__accountName with a value of your StorageAccountName instead of AzureWebJobsStorage with the connection string value.

**Comment by lsnoddy** [comment]
Pull request (https://github.com/Azure/ResourceModules/pull/1258) fixed the issue where the AzureWebJobsStorage app setting was added with an empty value if a storage account was not specified. The code will now omit the AzureWebJobsStorage app setting if storage account is not specified.
