### ISSUE TITLE
[Feature Request] BREAKING change: Rename `DEPLOYMENT_SP_ID` to `DEPLOYMENT_SPN_ENTAPP_OBJID`

### ISSUE THREAD

**Issue by MrMCake** [Azure/ResourceModules#1465]
### Description

As discussed in #1016, we want to be more explicit with the name of the `DEPLOYMENT_SP_ID` variable in CARML. In the past there was some confusion around this value.

Note: This is a breaking change that will require downstream forks/clones to update their environment.

**Comment by eriqua** [comment]
I totally support this change and I understand the team already agreed on this name, just wondering while N in SPN stands for Name, wouldn't it be better to call it `DEPLOYMENT_SP_ENTAPP_OBJID`?

In addition, since as correctly stated this is a breaking change and given 
- the open draft PR by @MariusStorhaug #1452 and
- the open pr #1472 by @SeSeicht 

I'd suggest to align on the name of all GH and ADO secrets in order not to introduce the same breaking change twice.
For example the OIDC PR should align with the name suggested by this actual feature request and similarly refer to `DEPLOYMENT_SP_ENTAPP_APPID` or `DEPLOYMENT_SP_APPID` instead of `ARM_CLIENT_ID` since we're talking about the same service principal.

**Comment by MariusStorhaug** [comment]
@eriqua As a SP consist of an EntApp and AppReg, I would suggest just calling it `DEPLOYMENT_SP_APPID` in that case as AppID is shared between the two, aligning more to object/class oriented naming.
Will review these PRs tomorrow to align a bit more.

**Comment by MariusStorhaug** [comment]
#1605 could make the rename obsolete.

**Comment by rahalan** [comment]
@MariusStorhaug please elaborate on your findings with your PoC. Can we close the issue?

**Comment by MariusStorhaug** [comment]
@rahalan, I don't think we should close it until we agree if we want to automate the step? If we do then this issue is redundant and should not be worked on. I have not taken that issue myself yet, and removed it from the PR regarding OIDC as its combining a lot of overhead to the PR which wasn't the intention in the first place.
