### ISSUE TITLE
[Feature Request] Add a step by step "how to create a solution"

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/ResourceModules#1518]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/learn-bicep

**Comment by eriqua** [comment]
The current wiki page solution creation contains theory about the difference between template vs pipeline orchestrated approach and code snippets on how to refer to modules published in different ways: template specs, registry, local repo or ado universal packages.

This issue is about providing a step by step guideline about how to create a solution from scratch. E.g.:

- Identify the resources needed for your architecture
- Identify dependencies between them
- Choose orchestration (template vs pipeline orchestrated approach). What are the pros/cons?
- Choose publishing (template specs, registry, local repo or ado universal packages). What are the pros/cons?
- Check readme file for each resource and identify parameters needed for your solution
- Based on orchestration and publishing decision build the solution. Ref to snippets and constructs
- Deploy the solution
