### ISSUE TITLE
[Feature Request]: Ability to consume CARML modules directly (Public Bicep Registry)

### ISSUE THREAD

**Issue by fblix** [Azure/ResourceModules#1645]
### Description

Is there currently a way to consume CARML modules directly without having to clone the repo and to publish each module again?

**Comment by JPEasier** [comment]
Would be nice for one of my customer projects to consume CARML modules from a public registry.

**Comment by MrMCake** [comment]
Hey @fblix,

great question and something which comes up every now and then. Originally the plan was to publish to the Public Bicep Registry on-scale, but until there is no way to automate this for us, it is on hold.

To operate our own Registry (with a public endpoint), we'd need to satisfy certain conditions:

- new, empty registry deployed (lock protected)
- clarify funding for the registry (the current registry resulted in about 40$ of consumption since its creation - in storage costs)
- establish a strict versioning process in CARML (i.e., maintain the `version.json` files on our end too)
- maintain a table of module versions that point to specific commits (to allow backtracking to an oder module code & readme) and expose the URL to a given version (for reference in a solution template) <p>
  For example 
  - 1 table with all latest module versions:
    | Module | Source | Url |
    | - | - | - | 
    |  Key Vault | [1.5](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.5` |
    | Storage Account | [1.7](https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Storage/storageAccounts) | `carml.azurecr.io/bicep/microsoft.storage.storageaccounts:1.5` |
    | ... | ... | ... |
  - 1 table per resource type exposing all published versions
    | Module | Source | Url |
    | - | - | - |
    |  Key Vault | [1.5](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.5` |
    |  Key Vault | [1.4](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.4` |
    |  Key Vault |[1.3](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.3` |
    |  Key Vault | [1.2](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.2` |
    |  Key Vault | [1.1.1](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.1.1` |
    |  Key Vault | [1.1.0](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.1.0` |
    |  Key Vault | [1.0](https://github.com/Azure/ResourceModules/tree/93e0c6367830bf2385ccaa2ecb5e2cede005d199/modules/Microsoft.KeyVault/vaults) | `carml.azurecr.io/bicep/microsoft.keyvault.vaults:1.0` |

**Comment by segraef** [comment]
Further points to be elaborated in addition to @MrMCake's initial comments:

- Find out current status of Bicep in ACR, are there any new preview features that can be used?
- Hard requirements on versioning process. 
- Private vs Public Bicep Registry
- Can HC TF Registry patterns taken into consideration where each module is stored on individual repositories? Would it increase maintenance? Would it simplify dependencies rather having all Modules in a single repository like it is currently?

Outlining the approach for the POC:

- Create new and empty registry (lock protection optional, only relevant internally)
- Test new preview features like [anonymous public access](https://docs.microsoft.com/en-us/azure/container-registry/anonymous-pull-access)
- Find out options how versioning can be achieved, dependent or independent to CARML
- If versioning dependent on CARML, should version.json be used?
- If versioning independent of CARML, how is 
- Since CARML is still in Beta, is a strict and dependent versioning required?
- Establish a strict versioning process
  - Example process: CARML module changed > (version.json changed) > PR > commit as reference in repo module and published versions
-

**Comment by segraef** [comment]
#2064

**Comment by segraef** [comment]
@fblix, can be achieved via https://docs.microsoft.com/en-us/azure/container-registry/anonymous-pull-access, we're currently elaborating options on how to implement it, please stand by.

**Comment by segraef** [comment]
I think we can close this one.
