### ISSUE TITLE
[Bug Report]: New GitHub method to set output (`>> $env:GITHUB_OUTPUT`) fails for some pipelines

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/ResourceModules#2323]
### Describe the bug

After converting the way GitHub handles Outputs to the `>> $env:GITHUB_OUTPUT` approach (as the original is scheduled to be deprecated) it turned out that this method cannot handle certain use cases like Multi-line strings, etc.

This is something we MUST resolve before the next release as it blocks pipelines from publishing even on a successful deployment:

![image](https://user-images.githubusercontent.com/5365358/201491320-f8b81ad3-b604-4eeb-8ec8-8e31e2b03cc4.png)

### To reproduce

Refer to the pipeline output of the [Synapse Workspace](https://github.com/Azure/ResourceModules/actions/runs/3451880254/jobs/5761426164) pipeline.

**Comment by eriqua** [comment]
The issue is currently impacting the generation of the `deploymentOutput` output parameter in the validateModuleDeployment action. 

The `deploymentOutput` output parameter was originally added to the validate deployment action (GH) and pipeline template (ADO) to support pipeline orchestration for the dependencies pipeline.
With the new self-contained dependencies approach, the `deploymentOutput` output parameter is not used by the CI environment and could hence be removed together with its generation code snippet.

A draft for this fix (commented code) is shown in PR #2327. It has been tested successfully with the Synapse Workspace pipeline.

If accepted, the change should be merged with PR #2297, currently blocked by issue #1791.

**Comment by AlexanderSehr** [comment]
Set to blocked until #1791 is resolved and the dependency pipeline is removed

**Comment by AlexanderSehr** [comment]
The dependency pipeline was removed and the failing output logic was removed as well.
