### ISSUE TITLE
[Feature Request]: new module for Microsoft.PowerBI/privateLinkServicesForPowerBI@2020-06-01

### ISSUE THREAD

**Issue by GeraldGoldstein** [Azure/ResourceModules#2460]
### Description

module for the deployment of PE's for power bi private access to tenant according to this page https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links

**Comment by AlexanderSehr** [comment]
Hey @GeraldGoldstein,
an absolutely valid request. Please note, since last September, we've been migrating all modules as per the [AVM](https://http//aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
