### ISSUE TITLE
[Feature Request]: module for Microsoft.Network/p2svpnGateways@2020-11-01 for hub deployment

### ISSUE THREAD

**Issue by GeraldGoldstein** [Azure/ResourceModules#2462]
### Description

provide a module to deploy P2S VPN into virtual wan hub

**Comment by AlexanderSehr** [comment]
Hey @GeraldGoldstein,
This is an absolut legit request. Please note, since last September, we've been migrating all modules as per the [AVM](https://http//aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
