### ISSUE TITLE
[Modules] Add Microsoft.Devices/IoTHubs module

### ISSUE THREAD

**Issue by samuel-peeters-pxs** [Azure/ResourceModules#2856]
The Azure/ResourceModules is missing the Microsoft.Devices/IoTHubs module.
I have a Bicep template available and was already succesfully deployed but will adhere to the contribution guidelines and set up the build environment.

**Comment by AlexanderSehr** [comment]
Hey @samuel-peeters-pxs, the contribution would be much appreciated. If you need any support, please let us know. We'll go ahead and assign you the issue too.

**Comment by AlexanderSehr** [comment]
Hey @samuel-peeters-pxs,
It has been a while. Please note, since last September, we've been migrating all modules as per the [AVM](https://http//aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
