### ISSUE TITLE
[Feature Request]: Add support for ServiceLinker

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/ResourceModules#2865]
### Description

it would be nice to have module(s) for https://learn.microsoft.com/en-us/azure/templates/microsoft.servicelinker/2022-01-01-preview/linkers?pivots=deployment-language-bicep

**Comment by AlexanderSehr** [comment]
Hey @davidkarlsen thanks for raising the suggestion.

**Comment by AlexanderSehr** [comment]
Hey @davidkarlsen,
it has been a whle. Please note, since last September, we've been migrating all modules as per the [AVM](https://http://aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
