### ISSUE TITLE
[Bug Report]: Bicep Lint - Warning use-resource-id-functions

### ISSUE THREAD

**Issue by rdtechie** [Azure/ResourceModules#2877]
### Describe the bug

While deploying a Virtual Machine I'm receiving this linter message:

```shell
/home/runner/work/ResourceModules/ResourceModules/modules/Microsoft.Compute/virtualMachines/deploy.bicep(485,9) : Warning use-resource-id-functions: If property "id" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]
```

Is this something that is already been addressed?

### To reproduce

Deploy a Virtual Machine from the Virtual Machines module.

**Comment by rdtechie** [comment]
Did work, receiving this message:

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6579452/223559899-224f5f03-c146-4386-aec5-3897f5c1a038.png">

**Comment by rdtechie** [comment]
Closing this issue as we're abandoning Bicep.

**Comment by AlexanderSehr** [comment]
> Didn't work, receiving this message:
> 
> <img alt="image" width="1727" src="https://user-images.githubusercontent.com/6579452/223559899-224f5f03-c146-4386-aec5-3897f5c1a038.png">

Hey @rdtechie, sorry that I didn't respond again. Even though you closed the issue I want to respond regardless in case somebody else encounters similar issues.

From the screenshot you sent, it appeears the place where the resource ID is declared is incorrect - or to be more precise - the place where it is declared doesn't match the place where it is referenced after.

Apparently the a single element of your `nicConfigurations` array looks similar to
```json
{
  ipConfigurations: (...),
  nicSuffix: (...) 
}
``` 

while you expect something like
```json
{
  ipConfigurations: (...),
  nicSuffix: (...),
  nicResourceId: (...)
}
``` 

That's why Bicep complains in this case as it doesn't find the property `nicResourceId` in the object you reference it from and raises that the only `"available properties are 'ipConfigurations' & 'nicSuffix'"`.  

Looking into the original suggestion a bit deeper I see now why it didn't work too. The `nicConfigurations` array is referenced in 2 places. First for creating the NICs and another time to reference it. In both cases, the original array is used, which is why it didn't help adding the `nicResourceId` output to the sub-module - the sub-modules output is simply never referenced.
To finally get rid of this 'warning' it would likely be necessary to switch the 2nd reference of the `nicConfigurations` to reference `vm_nic` instead and in that module return all reference you'd want to re-use (i.e., `deleteOption` & `nicResourceId`). In that case, the reference would look something like:

```bicep
networkProfile: {
  networkInterfaces: [for (nicConfiguration, index) in vm_nic: {
    properties: {
      deleteOption: contains(nicConfiguration, 'deleteOption') ? nicConfiguration.deleteOption : 'Delete'
      primary: index == 0 ? true : false
    }
    id: nicConfiguration[index].nicResourceId
  }]
}
```

and the output of the `vm_nic` array (in the `nested_networkInterface.bicep` file) like
```bicep
param deleteOption string // Just declared to return it again as part of the `vm_nic` output.

output deleteOption string = deleteOption
output nicResourceID string = networkInterface.outputs.resourceId
```

Again, I'm sorry for the late reply but wish you all the best with whatever alternative you're going with. 🚀
