### ISSUE TITLE
[Feature Request]: Need module for Azure Data Explorer `Microsoft.Kusto/clusters`

### ISSUE THREAD

**Issue by Lddeiva** [Azure/ResourceModules#2891]
### Description

As there is no module for **Azure Data Explorer** `Microsoft.Kusto/clusters` in this repository, I'm submitting this feature request to get a module.

**Comment by Lddeiva** [comment]
@AlexanderSehr , I was able to prepare the ADX module. I'll be submitting a basic version of the code which creates below. I'll submit the PR in the CARML repository by next week as I'm working on the readme files.

ADX Cluster with CMK
ADX Cluster Database
ADX Cluster Role Assignment
ADX Private Endpoints

**Comment by AlexanderSehr** [comment]
Hey @Lddeiva,
it has been a while. Please note, since last September, we've been migrating all modules as per the [AVM](https://http://aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose). I guess this ties to your draft PR: https://github.com/Azure/ResourceModules/pull/2892

Will close the issue for CARML though :)
