### ISSUE TITLE
[Question/Feedback]: a warning in Bicep file

### ISSUE THREAD

**Issue by jamesyoung007** [Azure/ResourceModules#3396]
### Description

File: modules/compute/virtual-machines/main.bicep

Line 478
id: az.resourceId('Microsoft.Network/networkInterfaces', '${name}${nicConfiguration.nicSuffix}')
warning: 
If property "id" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId.

Line 582
workspaceId: !empty(monitoringWorkspaceId) ? reference(vm_logAnalyticsWorkspace.id, vm_logAnalyticsWorkspace.apiVersion).customerId : ''
warning:
Use a resource reference instead of invoking function "reference". This simplifies the syntax and allows Bicep to better understand your deployment dependency graph.

Can I safely ignore them?

**Comment by AlexanderSehr** [comment]
Hey @jamesyoung007, yes you can safely ignore them. I don't have the code in front of me, but I believe in case of the NICs we cannot use a symbolic reference due to the loop around it.
The 2nd warning might be something we can update to a 'existing'  resource reference, but I'd need to check. It could be that it's implementated this way due to a Bicep limitation. 
In any case, both warnings are rather a code "styling" warning than something that could be harmful.

**Comment by AlexanderSehr** [comment]
I @jamesyoung007 I created a PR to get rid of one of the 2 warnings (#3410). As described in the previous comment, the one regarding the NICs unfortuantely needs to stay.
