### ISSUE TITLE
[Question/Feedback]: The linked property has values which are of invalid types 'Object'

### ISSUE THREAD

**Issue by dewolfs** [Azure/ResourceModules#3431]
### Description

Hi,

I want to create a VNET and multiple subnets. I create network security groups per subnet and associate to the subnets.

**vnet.bicep**
```javascript
module networkSecurityGroup 'modules/Microsoft.Network/networkSecurityGroups/deploy.bicep' = [for (sn, index) in vnet.subnets: {
  name: '${uniqueString(deployment().name, location)}-nsg-${sn.name}'
  scope: resourceGroup('network')
  params: {
    location: location
    name: '${abbrs.networkNetworkSecurityGroups}${sn.name}'
  }
}]

resource nsg 'Microsoft.Network/networkSecurityGroups@2021-02-01' existing = [for (sn, index) in vnet.subnets: {
  name: '${abbrs.networkNetworkSecurityGroups}${sn.name}'
  scope: resourceGroup('network')
}]

module virtualNetwork 'modules/Microsoft.Network/virtualNetworks/deploy.bicep' = {
  name: '${uniqueString(deployment().name, location)}-virtualNetwork'
  scope: resourceGroup('network')
  params: {
    location: rgNetwork.outputs.location
    addressPrefixes: vnet.addressPrefixes
    name: vnet.virtualNetworkName
    subnets: [for (sn, index) in vnet.subnets: {
      name: sn.name
      addressPrefix: sn.subnetPrefix
      networkSecurityGroupId: {
        id: nsg[index].id
      }
    }
    ]
  }
  dependsOn: [
    networkSecurityGroup
    nsg
  ]
}
```
**vnet.bicepparam**
```javascript
param vnet = {
    virtualNetworkName: 'vnet1'
    addressPrefixes: [
        '20.0.0.0/24'
    ]
    subnets: [
        {
            name: 'snet-frontend-001'
            subnetPrefix: '20.0.0.0/26'
        }
        {
            name: 'snet-backend-001'
            subnetPrefix: '20.0.0.64/26'
        }
    ]
}
```
I use the [VNET ](https://github.com/Azure/ResourceModules/tree/main/modules/network/virtual-networks)and [SecurityGroup](https://github.com/Azure/ResourceModules/tree/main/modules/network/network-security-groups) CARML modules.

When I try to deploy this template I get the error:

_"details":[{"code":"LinkedAuthorizationFailed","message":"The client has permission to perform action 'Microsoft.Network/virtualNetworks/write' on scope '/subscriptions/xxxxxx/resourcegroups/network/providers/Microsoft.Network/virtualNetworks/vnet1'; however, the linked  property 'properties.subnets[*].properties.networkSecurityGroup.id' has values which are of invalid types 'Object'._

However, when I don't the use the CARML modules and use the resource VNET (resource VNET 'Microsoft.Network/virtualNetworks@2021-02-01') it does work.

**Comment by AlexanderSehr** [comment]
Hey @dewolfs,
please excuse the late reply. I just checked the examples of the VNET deployment (i.e., from the readme, as well as our test cases) and it appears the module expects simply the resourceID string instead of the object as in the resource provider:

https://github.com/Azure/ResourceModules/blob/1b8bee3ad9920704b0b76158d30ab16f2293c030/modules/network/virtual-networks/.test/common/main.test.bicep#L99

the implementation in the module is:

https://github.com/Azure/ResourceModules/blob/1b8bee3ad9920704b0b76158d30ab16f2293c030/modules/network/virtual-networks/main.bicep#L170-L172

The reason this is implemented this way (as is the case for route tables and other modules) is that we opted to simplify the deployment of references if the reference object only contains one property. In the given example, instead of expecting the user to provide an object such as `{ id: 'subscriptions/(...)' }` it's enough to provide the `'subscriptions/(...)'`.

If this is still confusing (as you may notice I'm not the best at explaining), let's 'update' your example above which will hopefully help:

```bicep
module networkSecurityGroup 'modules/Microsoft.Network/networkSecurityGroups/deploy.bicep' = [for (sn, index) in vnet.subnets: {
  name: '${uniqueString(deployment().name, location)}-nsg-${sn.name}'
  scope: resourceGroup('network')
  params: {
    location: location
    name: '${abbrs.networkNetworkSecurityGroups}${sn.name}'
  }
}]

resource nsg 'Microsoft.Network/networkSecurityGroups@2021-02-01' existing = [for (sn, index) in vnet.subnets: {
  name: '${abbrs.networkNetworkSecurityGroups}${sn.name}'
  scope: resourceGroup('network')
}]

module virtualNetwork 'modules/Microsoft.Network/virtualNetworks/deploy.bicep' = {
  name: '${uniqueString(deployment().name, location)}-virtualNetwork'
  scope: resourceGroup('network')
  params: {
    location: rgNetwork.outputs.location
    addressPrefixes: vnet.addressPrefixes
    name: vnet.virtualNetworkName
    subnets: [for (sn, index) in vnet.subnets: {
      name: sn.name
      addressPrefix: sn.subnetPrefix
      networkSecurityGroupId: nsg[index].id    // This is the change <---
    }
    ]
  }
  dependsOn: [
    networkSecurityGroup
    nsg
  ]
}
```

> Note: This is also why the expected property is called `networkSecurityGroupId` (though it should be `networkSecurityGroupResourceId`) instead of the resource provider's `networkSecurityGroug`.

**Comment by dewolfs** [comment]
@AlexanderSehr thank you for the explanation.
I was able to execute a successful deployment.

Thx!
