### ISSUE TITLE
[Bug Report]:  used resource type [privateEndpoints] should use one of the recent API version(s). Currently using [2022-07-01]

### ISSUE THREAD

**Issue by ChrisGibson1982** [Azure/ResourceModules#3875]
### Describe the bug

The modules in the repo that use the network resource "private endpoints" are failing the pipelines with the below error.

##[error]   [-] In [event-hub/namespace] used resource type [privateEndpoints] should use one of the recent API version(s). Currently using [2022-07-01]. 48ms (47ms|1ms)

Updating the API version of this module is easy enough, but updating the readme files and getting them to pass the pester tests is a bit more difficult.  Is there a plan to update these resource versions?

### To reproduce

Run the "EventHub - Namespaces" or "KeyVault - Vaults" pipeline against the current main branch

### Relevant log output

```Shell
##[error]   [-] In [key-vault/vault] used resource type [privateEndpoints] should use one of the recent API version(s). Currently using [2022-07-01]. 29ms (28ms|1ms)
##[error]    Expected '2022-07-01' to be found in collection @('2023-05-01', '2023-04-01', '2023-02-01', '2022-11-01', '2022-09-01'), but it was not found.
##[error]    at $approvedApiVersions | Should -Contain $TargetApi, /home/vsts/work/1/s/utilities/pipelines/staticValidation/module.tests.ps1:1655
##[error]    at <ScriptBlock>, /home/vsts/work/1/s/utilities/pipelines/staticValidation/module.tests.ps1:1655
```

**Comment by AlexanderSehr** [comment]
Hey @ChrisGibson1982,
Thanks for raising this. Usually we try to fix those issues on our end asap. The currently used version is now [2023-04-**](https://github.com/Azure/ResourceModules/tree/main/modules/network/private-endpoint).
As you said, the fix is usually quick and I'd recommend to always use the Set-ModuleReadme script (in /utilities/tools) to update the Readme for you. It's the same function that is run in the pipeline to check if the Readme is up to date.
If you'd agree, we could close this issue 😊

**Comment by ChrisGibson1982** [comment]
Hi @AlexanderSher,

Sorry i missed your reply.  Yes this is fixed in main now

Thanks,

Chris
