### ISSUE TITLE
[Feature Request]: Monitoring workspace for AKS Cluster

### ISSUE THREAD

**Issue by osagiestar** [Azure/ResourceModules#4046]
### Description

Monitoring workspace module which is a pre-requisite for Managed Promitheus deployment for AKS Cluster is not yet available on Azure ResourceModules repository ( container/managed cluster ). 

dependencies.bicep file:
```bicep
resource monitoringWorkspace 'Microsoft.Monitor/accounts@2023-04-03' = {
  name: monitoringWorkspaceName
  location: location
}
```
main.bicep file: 
```bicep
monitoringWorkspaceId: nestedDependencies.outputs.workspaceResourceId
```
This is missing, hence this feature request.

**Comment by AlexanderSehr** [comment]
Hey @osagiestar ,
you're right on that. Please note, since last September, we've been migrating all modules as per the [AVM](https://http://aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
