### ISSUE TITLE
[Bug Report]: User-defined-types causing errors

### ISSUE THREAD

**Issue by Chrisrehpot** [Azure/ResourceModules#4153]
### Describe the bug

There are errors in the main.bicep files of many modules 

For example in network/private-endpoint :
"param applicationSecurityGroupResourceIds array? "   should be "param applicationSecurityGroupResourceIds array []"

For example in storage/storage-account\main.bicep 
"param roleAssignments roleAssignmentType " should be "param roleAssignments array = [] "

### To reproduce

Nothing to reproduce

**Comment by AlexanderSehr** [comment]
Good day @Chrisrehpot, and thanks for opening the issue.

The cases you describe are actually not bugs, but the result of the implementation of User-defined-types we're currently rolling out for (but not limited to) the extension resources Private Endpoints, Role Assignments, Managed Identities, etc.

I assume you're facing issues using the modules with this new Bicep feature. May I ask where exactly this happens? One scenario I can imagine is that you're using the CARML CI of version `0.11.1` which did not yet support User-defined-types and hence e.g. the ReadMe utility fails handling them. I guess that, because I was one of those working on actually making the tools compatible. Please let me know and I'll try to help :)

**Comment by Chrisrehpot** [comment]
Hi Alexander,
I don't know what CARML CI is
Here are the issues I"m experiencing. The modules in VScode are in error
Thanks for your help

![4f5be96f-4b37-42df-9e76-1abed598ce70](https://github.com/Azure/ResourceModules/assets/149106465/10592b52-0793-4680-be95-05b22605c0ca)
![69765d00-bfd3-41ce-be4d-18a763125448](https://github.com/Azure/ResourceModules/assets/149106465/9b92a436-a9e3-492b-a110-957990cd4c9f)

**Comment by AlexanderSehr** [comment]
Hey @Chrisrehpot if you don't know what it is may make resolving the issue a lot easier.
May I ask which Bicep version you're running?
You can check this by running the following 2 commands:

```PowerShell
bicep --version
az bicep version
```

My best guess is that the version you're using may not yet support user defined types, so we should rule that out first.

**Comment by AlexanderSehr** [comment]
Background: What you're looking at are 2 features:
1 . Are the aforementioned user defined types. Those are defined at the bottom of the template and have the `type` identifier. What they enable you to do is to describe how an object / array looks like so that users have an easier time interacting with them
1. Nullable types (which are available for any type, by it user-defined or not (like string)). Those are identified by that little `?` at the end of the type. In turn, they enable you to declare a parameter as nullable, i.e. optional explicitely. Before that feature was available, you had to either provide a default (making the parameter optional), or not, making it required. However, for some parameters you may not want to define a default, which is now possible thanks to the nullable feature.

**Comment by Chrisrehpot** [comment]
Version : Bicep CLI version 0.16.1 (d77dcc750a)

**Comment by AlexanderSehr** [comment]
alright, so then that's likely the issue. Please update your Bicep version to the latest [0.22.6](https://github.com/Azure/bicep/releases/tag/v0.22.6). The feature was moved out of the 'experimental' state with version `0.21.1` just recently in September. 
Please let me know if that helped.

**Comment by Chrisrehpot** [comment]
Works fine this way. Thank you for your help

**Comment by AlexanderSehr** [comment]
Glad to help :)
