### ISSUE TITLE
[Bug Report]: Storage Account Bicep Linting - Warning BCP329

### ISSUE THREAD

**Issue by russellds** [Azure/ResourceModules#4250]
### Describe the bug

Getting the following linting warning when using the Storage Account module:

``` cmd
WARNING: ...\modules\storage\storage-account\blob-service\main.bicep(82,24) : Warning BCP329: The provided value can be as small as 0 and may be too small to assign to a target with a configured minimum of 1.
```

### To reproduce

Use Storage Account bicep module to deploy a storage account.

**Comment by AlexanderSehr** [comment]
Hey @russellds, 
thanks for brining this up. This seems to be an issue with this line:
```Bicep
retentionInDays: changeFeedEnabled == true ? (changeFeedRetentionInDays != 0 ? changeFeedRetentionInDays : null) : null
```
in which `retentionInDays` must be larger than 0, yet the parameter `changeFeedRetentionInDays` can be 0. 

As you may already figured by looking at the above if else statement, this is actually a false-positive. If `changeFeedRetentionInDays` were to be 0, Bicep would actually set the value to `null` not 0. 

I can only assume this was implemented this way because originally, it wasn't able to specify optional parameter in Bicep without also providing a default (in this case `0`).

Now that `nullable` types are available, the parameter could change to something like `param changeFeedRetentionInDays int?` and the logic in the template could change to
```Bicep
param changeFeedRetentionInDays int?

(...)
retentionInDays: changeFeedRetentionInDays
(...)
```
