### ISSUE TITLE
Align `insights/private-link-scope` to AVM specs

### ISSUE THREAD

**Issue by ahmadabdalla** [Azure/ResourceModules#4413]

**Comment by ahmadabdalla** [comment]
Work started
https://github.com/ahmadabdalla/bicep-registry-modules/tree/users/ahmad/4413_privateLinkScopes

**Comment by ahmadabdalla** [comment]
@AlexanderSehr @matebarabas Is this telemtry name correct for the AVM module?

`46d3xbcp.res.insights-privatelinkscopeopstatus`

It contains `opstatus` at the end, and doesn't align with other modules




</body>
</html>

**Comment by AlexanderSehr** [comment]
Hey @ahmadabdalla, I agree that looks a bit off. These are all insights modules we're tracking in the index table 
![image](https://github.com/Azure/ResourceModules/assets/5365358/da14dba7-98bc-431d-97a3-f920f2828ce0)

while the resource types of the module are
![image](https://github.com/Azure/ResourceModules/assets/5365358/651970ff-1010-4b45-accd-924ca76de164)

@matebarabas, this must be fixed in the CSV. Further, I guess the current, incorrect resource type is also incorrectly listed in the platform and we need an update of the corresponding GitHub repository before publishing the module.

**Comment by matebarabas** [comment]
@ahmadabdalla, I've just fixed the incorrect entry. Thank you for raising this to our attention! 👍

**Comment by ahmadabdalla** [comment]
Work completed
