### ISSUE TITLE
[Feature Request]: Microsoft.HybridCompute/privateLinkScopes module

### ISSUE THREAD

**Issue by Grant-Rc** [Azure/ResourceModules#4536]
### Description

Morning all

Loving the modules as it alot of effort taken care of up front. I was woundering if anyone was working on Microsoft.HybridCompute/privateLinkScopes module? This is for the deployments of ARC and i dont seem to see this in any module

**Comment by AlexanderSehr** [comment]
Hey @Grant-Rc,
you're right on that. Please note, since last September, we've been migrating all modules as per the [AVM](https://http://aka.ms/avm) (Azure-Verified-Modules) specs to AVM-modules that are published in the Public Bicep Registry. This repository in turn will 'only' be continued as a CI for inner sourcing.

That being said, the request is absolutely legit, and I'd invite you to create a module proposal [here](https://github.com/Azure/Azure-Verified-Modules/issues/new/choose).

Will close the issue for CARML though :)
