### ISSUE TITLE
Align resource names and update Wiki

### ISSUE THREAD

**Issue by rahalan** [Azure/ResourceModules#796]
The name of the deployed resources does not follow a strict naming convention. This one needs to be defined, documented and the parameter files changed accordingly.

**Comment by MrMCake** [comment]
This issue is about the resource names in the parameter files, usually applying a pattern such as 'sxx-az-<type>-x-001'. 

We opted to use the `x` to give the deployment a refernces, by replacing the `x` with the prefix of the parameter file itself (if any). 
For example, if the parmaeter file is called `min.parameters.json` we could call the resource `sxx-az-<type>-min-001`
